<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../src/ADLCompiler/ADLCompiler.csproj" />
    <ProjectReference Include="../src/SharedUtilities/SharedUtilities.csproj" />
  </ItemGroup>
</Project>
